=== rms1000watt/aiserver/aisdocsdev/trunk/DTD/Example.dtd
<?xml version="1.0" encoding="UTF-8"?>
 <!ELEMENT Example (KnowledgeBase, Description, Syntax)>
	 <!ELEMENT KnowledgeBase (Title, Template, FunctionKeywords, TypeKeywords, RelatedFunctions, Language, HumanKeywords)>
		<!ELEMENT Title (#PCDATA)>
		<!ELEMENT Template (#PCDATA)>
		<!ELEMENT FunctionKeywords (#PCDATA)>
		<!ELEMENT TypeKeywords (#PCDATA)>
		<!ELEMENT RelatedFunctions (#PCDATA)>
		<!ELEMENT Language (#PCDATA)>
		<!ELEMENT HumanKeywords (#PCDATA)>
	<!ELEMENT Description ANY>   
	<!ELEMENT Syntax ((Expression, Note, Returns)+,  Hints)>
		<!ELEMENT Expression ANY>
		<!ELEMENT Note ANY>
		<!ELEMENT Returns ANY>
		<!ELEMENT Hints ANY>
<!-- end -->

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_Number_isIdentical_009.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example Number isIdentical 009</Title>
		<Template>Example</Template>
		<FunctionKeywords>isIdentical</FunctionKeywords>
		<TypeKeywords>  Number</TypeKeywords>
		<RelatedFunctions>compareEQ isIdentical comparison isEqual     </RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>   Equal Analytic Object Boolean Number</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ This example  shows how an Integer and a Number Data type may be evaluated as identical by the



                  <b>isIdentical</b> function.




 










	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>(setq A 1)                   </sc>]]></Expression>  
        <Note><![CDATA[none]]></Note> 
        <Returns><![CDATA[1]]></Returns>
  	    <Expression><![CDATA[ <sc>(setq B 1.0)                   </sc>]]></Expression>  
        <Note><![CDATA[none]]></Note> 
        <Returns><![CDATA[1.0]]></Returns>
        <Expression><![CDATA[ <sc>(isIdentical A B)              </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[true]]></Returns>
        <Hints><![CDATA[ none  ]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_Number_nmod_001.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example Number nmod 001</Title>
		<Template>Example</Template>
		<FunctionKeywords>nmod</FunctionKeywords>
		<TypeKeywords>Integer Boolean Number</TypeKeywords>
		<RelatedFunctions>nadd nsub nmul ndiv</RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>number arithmetic division remainder mod  operators</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples use the <b>nmod</b> function to divide two Number objects and return








                 the remainder of the division operation as a Number value.

	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>
(nmod  12.2  3  )                     </sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[3.051757807758E-006]]></Returns>
 	    <Expression><![CDATA[ <sc>
(nmod  12.5  5.0)          </sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[2.5]]></Returns>
        <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_FltVector_map_005.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example FltVector map 005</Title>
		<Template>Example</Template>
		<FunctionKeywords>map</FunctionKeywords>
		<TypeKeywords>FltVector  </TypeKeywords>
		<RelatedFunctions>mapc new</RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>map mapc copy process</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ This example defines a FltVector and applies the <b>add1</b>
                 function to each element of the Vector using the  <b>map</b> function.   



                



	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>(define Scores  #(float| 5.456699848175 3.141592025757 ) ) </sc>]]></Expression>
        <Note><![CDATA[A Float Vector is defined. ]]></Note>
        <Returns><![CDATA[#&#60FltVector 123456&#62 ]]></Returns>
        <Expression><![CDATA[ <sc>(setq  NewScores  (map  add1  Scores))      </sc>]]></Expression>
        <Note><![CDATA[Increments the values by  one.]]></Note>
        <Returns><![CDATA[#&#60FltVector 123456&#62 ]]></Returns>
        <Expression><![CDATA[ <sc>  NewScores[0]  </sc>]]></Expression>
        <Note><![CDATA[Displays the resulting Vector.]]></Note>
        <Returns><![CDATA[6.456699848175]]></Returns>
        <Expression><![CDATA[ <sc>  NewScores[1]  </sc>]]></Expression>  
        <Note><![CDATA[none]]></Note> 
        <Returns><![CDATA[4.140999794006]]></Returns>
        <Hints><![CDATA[none
       ]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_PcodeVector_isAtom_009.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example PcodeVector isAtom 009</Title>
		<Template>Example</Template>
		<FunctionKeywords>isAtom</FunctionKeywords>
		<TypeKeywords>PcodeVector Boolean Pair List</TypeKeywords>
		<RelatedFunctions>isPair</RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>atom pair list non-list</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples check whether the object evaluated is




                  a Pair or not.  




	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc> (setq X (new Vector:  pcode: 5 4 ))    </sc>]]></Expression>  
        <Note><![CDATA[none ]]></Note> 
        <Returns><![CDATA[#&#60PcodeVector 123456&#62]]></Returns>
  	    <Expression><![CDATA[ <sc>(isAtom X )  </sc>]]></Expression>
        <Note><![CDATA[The evaluated object is a Vector, not a Pair, so true is returned. ]]></Note>
        <Returns><![CDATA[true]]></Returns>
        <Expression><![CDATA[ <sc>(isAtom  '(1  2))   </sc>]]></Expression>
        <Note><![CDATA[The evaluated object is a  Pair, so false is returned. ]]></Note>
        <Returns><![CDATA[false]]></Returns>
        <Hints><![CDATA[none ]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_IntVector_setCdr_007.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example IntVector setCdr 007</Title>
		<Template>Example</Template>
		<FunctionKeywords>setCdr</FunctionKeywords>
		<TypeKeywords>IntVector</TypeKeywords>
		<RelatedFunctions>ref refValues refAttributes cdr</RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>tail ref index cdr setCdr</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ This example defines a Vector and sets the  value







                  of the defined Vector using the <b>setCdr</b> function.  The <b>cdr</b>
                  expression is a Text.




	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>(setq X (setCdr #(int| 11 12 )   "tail")  )    </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[#&#60IntVector 188141&#62 ]]></Returns>
        <Expression><![CDATA[ <sc> (display X )    </sc>]]></Expression>
        <Note><![CDATA[Displays the contents of the Vector.]]></Note>
        <Returns><![CDATA[#(int| 11 12  . "tail") ]]></Returns>
        <Hints><![CDATA[none ]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_Number_abs_001.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example Number abs 001</Title>
		<Template>Example</Template>
		<FunctionKeywords>abs</FunctionKeywords>
		<TypeKeywords>Number</TypeKeywords>
		<RelatedFunctions>  </RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>absolute value</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[  <p> The <b>abs</b> function returns the absolute of all the numbers in the argument list. </p>
	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>
(abs 12)   </sc>   ]]></Expression>
        <Note><![CDATA[The absolute value of the Integer argument is returned.]]></Note>
        <Returns><![CDATA[12.0]]></Returns>
        <Expression><![CDATA[ <sc>(abs -4)   </sc>   ]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[4.0]]></Returns>
        <Expression><![CDATA[ <sc>(abs 42.45)   </sc>   ]]></Expression>  
        <Note><![CDATA[The absolute value of the Number argument is returned.]]></Note> 
        <Returns><![CDATA[42.45]]></Returns>     
         <Expression><![CDATA[ <sc>(abs #c1.0+2.0i)   </sc>   ]]></Expression>  
        <Note><![CDATA[The absolute value of the Complex Number argument is returned.]]></Note> 
        <Returns><![CDATA[2.2360679775]]></Returns>
        <Hints><![CDATA[none

        ]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_String_substitute_001.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example String substitute 001</Title>
		<Template>Example</Template>
		<FunctionKeywords>substitute</FunctionKeywords>
		<TypeKeywords>String Text Integer</TypeKeywords>
		<RelatedFunctions>replace rept </RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>replace substitute substring</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ This example shows the <b>substitute</b> function modifying
                  a substring of a given Text or String with a specified Text or String.
	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>(setq S  (new String:  "Small World"))      </sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[Small World]]></Returns>
        <Expression><![CDATA[ <sc>(setq S (substitute S "Small" "Old") )    </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[ Old World ]]></Returns>
        <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_Number_asin_001.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example Number asin 001</Title>
		<Template>Example</Template>
		<FunctionKeywords>asin</FunctionKeywords>
		<TypeKeywords>Number Integer</TypeKeywords>
		<RelatedFunctions> acos atan </RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>arc sine</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples use the <b>asin</b> function to compute the arc sine
                  of the argument.

	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>(asin 0) </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[0]]></Returns>
        <Expression><![CDATA[ <sc>(asin -1)</sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[-1.570796326795]]></Returns>
        <Expression><![CDATA[ <sc>(asin 1) </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[1.570796326795]]></Returns>
        <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>
