=== rms1000watt/aiserver/aisdocsdev/trunk/DTD/Example.dtd
<?xml version="1.0" encoding="UTF-8"?>
 <!ELEMENT Example (KnowledgeBase, Description, Syntax)>
	 <!ELEMENT KnowledgeBase (Title, Template, FunctionKeywords, TypeKeywords, RelatedFunctions, Language, HumanKeywords)>
		<!ELEMENT Title (#PCDATA)>
		<!ELEMENT Template (#PCDATA)>
		<!ELEMENT FunctionKeywords (#PCDATA)>
		<!ELEMENT TypeKeywords (#PCDATA)>
		<!ELEMENT RelatedFunctions (#PCDATA)>
		<!ELEMENT Language (#PCDATA)>
		<!ELEMENT HumanKeywords (#PCDATA)>
	<!ELEMENT Description ANY>   
	<!ELEMENT Syntax ((Expression, Note, Returns)+,  Hints)>
		<!ELEMENT Expression ANY>
		<!ELEMENT Note ANY>
		<!ELEMENT Returns ANY>
		<!ELEMENT Hints ANY>
<!-- end -->

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_BitVector_new_013.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example BitVector new 013</Title>
		<Template>Example</Template>
		<FunctionKeywords>new</FunctionKeywords>
		<TypeKeywords> BitVector</TypeKeywords>
		<RelatedFunctions> setq  define </RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>new pointer create initialize</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples show how to construct a typed Vector.

                  A Bit Vector is constructed using the

                  <b>new</b> function.

	]]></Description>
	<Syntax>
	    <Expression><![CDATA[ <sc>(new Vector:  Bit: 5  1)                </sc>]]></Expression>
        <Note><![CDATA[Returns a Bit Vector of all 1's.]]></Note>
        <Returns><![CDATA[#&#60BitVector 123456&#62]]></Returns>
        <Expression><![CDATA[ <sc>(display #&#60BitVector 123456&#62)    </sc>]]></Expression>
        <Note><![CDATA[ Displays the contents of the Bit Vector.]]></Note>
        <Returns><![CDATA[#(bit| 1 1 1 1 1 )]]></Returns>
        <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_ByteVector_isCharName_003.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example ByteVector isCharName 003</Title>
		<Template>Example</Template>
		<FunctionKeywords>isCharName</FunctionKeywords>
		<TypeKeywords>Text Character String Symbol ByteVector </TypeKeywords>
		<RelatedFunctions>isType isChar isCharAlphabetic isCharAlphanumeric



                          isCharLowercase isCharNumeric isCharUppercase isCharWhitespace



                          isString isText </RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>Character Alphabetic Object Uppercase Lowercase Name



                       Underscore Numeric Alphanumeric Name Whitespace</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples check if the object is is made up of alphanumeric or underscore



                  characters. If it is,  the function returns true, otherwise, it returns false.



 



	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>(isCharName  #\p)  </sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[true]]></Returns>
        <Expression><![CDATA[ <sc>(isCharName "My Name is Anna") </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[ false ]]></Returns>
        <Expression><![CDATA[ <sc>(isCharName Ab_de:) </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[ true ]]></Returns>
        <Expression><![CDATA[ <sc>(isCharName  abc:)</sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[ true ]]></Returns>
        <Expression><![CDATA[ <sc>(isCharName  #&#60Dictionary 47917&#62) </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[ false ]]></Returns>
        <Hints><![CDATA[This function returns false if there are whitespaces between



               alphanumeric or underscore characters.]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_NumMatrix_append_012.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example NumMatrix append 012</Title>
		<Template>Example</Template>
		<FunctionKeywords>append</FunctionKeywords>
		<TypeKeywords>NumMatrix</TypeKeywords>
		<RelatedFunctions>new replace rept</RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>append concatenate  matrix </HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ This example takes an existing Number Matrix and appends a new number values.

	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>(define X #(nummat| 3 5 3 2 1 ) )      </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[#&#60NumMatrix 123456&#62 ]]></Returns>
        <Expression><![CDATA[ <sc>(define Y #(nummat| 12 14 15 ) )       </sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[#&#60NumMatrix 234567&#62   ]]></Returns>
        <Expression><![CDATA[ <sc>(define Z #(nummat| 21 25 26 22) )         </sc>]]></Expression>  
        <Note><![CDATA[none]]></Note> 
        <Returns><![CDATA[#&#60NumMatrix 345678&#62   ]]></Returns>
        <Expression><![CDATA[ <sc>(setq W (append X Y Z ))      </sc>]]></Expression>  
        <Note><![CDATA[none]]></Note> 
        <Returns><![CDATA[#&#60NumMatrix 456789&#62   ]]></Returns>
        <Expression><![CDATA[ <sc>(display #&#60NumMatrix 456789&#62 )       </sc>]]></Expression>
        <Note><![CDATA[Use the display command to display the contents of the appended Matrix. Note
              that Matrix X, Y and Z are not modified. ]]></Note>
        <Returns><![CDATA[#(nummat| 3.0 5.0 3.0 2.0 1.0 12.0 14.0 15.0 21.0 25.0 26.0 22.0 )]]></Returns>
        <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_ShortVector_isType_018.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example ShortVector isType 018</Title>
		<Template>Example</Template>
		<FunctionKeywords>isType</FunctionKeywords>
		<TypeKeywords>IntVector Boolean String </TypeKeywords>
		<RelatedFunctions>  isObject isText isIntegerVector isBitVector 


                          isNumberVector isByteVector isIdentical isFloatVector


                           isObjectVector isPcodeVector isVector</RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>Type Analytic Object</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[
                  The <b>isType</b> function is used to check if the argument object is









                  of the correct type.







                  If it is,  the function returns true, otherwise, it returns false.







 










	]]></Description>
	<Syntax>
        <Expression><![CDATA[ <sc>(setq Y (new Vector:  short:  2  11 12) )           </sc>]]></Expression>
        <Note><![CDATA[A Short Vector is defined.]]></Note>
        <Returns><![CDATA[#&#60ShortVector 123456&#62]]></Returns>
        <Expression><![CDATA[ <sc>(isType  ShortVector: Y)      </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[ true ]]></Returns>
        <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_String_substringCiGE_001.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example String substringCiGE 001</Title>
		<Template>Example</Template>
		<FunctionKeywords>substringCiGE</FunctionKeywords>
		<TypeKeywords>String Integer</TypeKeywords>
		<RelatedFunctions>substringCiEQ substringCiNE substringCiGT substringCiLT substringCiLE</RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>compare string equal boolean case-insensitive substring greater</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples use the <b>substringCiGE</b> function to see if the first substring is
                  greater than or equal to the second substring and return
the Boolean value, true or false. In these examples, a case-insensitive comparison

                  is done with the substrings.

	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc> (define X "Central Park")  </sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[Central Park ]]></Returns>
        <Expression><![CDATA[ <sc> (define Y "Jurassic Park")  </sc>]]></Expression>  
        <Note><![CDATA[none]]></Note> 
        <Returns><![CDATA[Jurassic Park ]]></Returns>
        <Expression><![CDATA[ <sc>(substringCiGE  X 0 6 Y 0 8)   </sc>]]></Expression>  
        <Note><![CDATA[Compares  "Central" in X and "Jurrasic" in Y .  ]]></Note> 
        <Returns><![CDATA[false]]></Returns>
        <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_Boolean_compare_009.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example Boolean compare 009</Title>
		<Template>Example</Template>
		<FunctionKeywords>compare</FunctionKeywords>
		<TypeKeywords>Boolean Integer</TypeKeywords>
		<RelatedFunctions>comparison compareEQ compareGT compareNE compareLT  compareLE</RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>compare symbol equal lesser </HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples use the <b>compare</b> functions to do a 








                  case-sensitive comparison of two objects of the same type.  A Boolean value is returned.








	]]></Description>
	<Syntax>
        <Expression><![CDATA[ <sc>(compare false  0 )           </sc>]]></Expression>
        <Note><![CDATA[ The value of the first object is lesser than the value

               of the second object.]]></Note>
        <Returns><![CDATA[-1]]></Returns>
        <Expression><![CDATA[ <sc>(compare false #\space )        </sc>]]></Expression>
        <Note><![CDATA[ The value of the first object is lesser than the value





               of the second object.]]></Note>
        <Returns><![CDATA[-1]]></Returns>
        <Expression><![CDATA[ <sc>(compare false #void )          </sc>]]></Expression>
        <Note><![CDATA[ The value of the first object is greater than the value
               of the second object.]]></Note>
        <Returns><![CDATA[1]]></Returns>
        <Expression><![CDATA[ <sc>(compare false (&#62 2 3))            </sc>]]></Expression>  
        <Note><![CDATA[False has a state value of 1 while the result of the &#62 operation is also 1. ]]></Note> 
        <Returns><![CDATA[0]]></Returns>
        <Hints><![CDATA[
           <p>If you prefer a Boolean  resulting from the comparison , use the compareEQ, compareNE, compareGT, compareLT functions.</p>
        ]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_Structure_new_003.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example Structure new 003</Title>
		<Template>Example</Template>
		<FunctionKeywords>new</FunctionKeywords>
		<TypeKeywords>Structure Symbol Integer</TypeKeywords>
		<RelatedFunctions>string makeStructure define defineStructure</RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>new pointer create initialize</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples show how to create an instance of

                  a Structure through the <b>new</b> function.

                  The <b>new</b> function initializes the


	              Structures with the specified bindings.

	]]></Description>
	<Syntax>
	    <Expression><![CDATA[ <sc>(setq Employee  (new Structure:  Name: "John Doe"  Title:  "Director"))   </sc>]]></Expression>
        <Note><![CDATA[ Create a new structure, named Employee, and initialize it with two bindings.]]></Note>
        <Returns><![CDATA[#&#60Structure 123456&#62]]></Returns>
        <Expression><![CDATA[ <sc>(display Employee)     </sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[ #{Name: "John Doe" Title: "Director"}]]></Returns>
  	    <Expression><![CDATA[ <sc>(setq  aStruct   (new Structure:  X:  22  Y:  34  .  3))    </sc>]]></Expression>
        <Note><![CDATA[Create a new structure, aStruct and initialize it with two bindings and cdr]]></Note>
        <Returns><![CDATA[#&#60Structure 123456&#62]]></Returns>
        <Expression><![CDATA[ <sc>(cdr aStruct)       </sc>]]></Expression>  
        <Note><![CDATA[Displays the cdr value of aStruct.]]></Note> 
        <Returns><![CDATA[3]]></Returns>
        <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_Matrix_ref_016.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example Matrix ref 016</Title>
		<Template>Example</Template>
		<FunctionKeywords>ref</FunctionKeywords>
		<TypeKeywords> Matrix Text String Integer</TypeKeywords>
		<RelatedFunctions>setq  ref fieldsOf   refValues  </RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>ref reference set position</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ This examples show the shorthand form of Matrix reference through

                  the bracket [] operators. In this example, the Matrix value is referenced 

                  by using its index. The <b>ref</b> function is used either with the Matrix Name or the 

                  Matrix' Object ID.
  

	]]></Description>
	<Syntax>
	    <Expression><![CDATA[ <sc>(define Fruits  #(mat| "apple" "orange" "lemon"))          </sc>]]></Expression>  
        <Note><![CDATA[Define a Matrix containing various fruit names: ]]></Note> 
        <Returns><![CDATA[#&#60Matrix 123456&#62 ]]></Returns>
        <Expression><![CDATA[ <sc>(setq Food  (new Matrix: 2 2 2 "apple" "orange" "lemon" "Pair"))  </sc>]]></Expression>  
        <Note><![CDATA[Define another Matrix.]]></Note> 
        <Returns><![CDATA[#&#60Matrix 234567&#62 ]]></Returns>
        <Expression><![CDATA[ <sc>Fruits [0] </sc>]]></Expression>
        <Note><![CDATA[Accesses the Matrix value with index 0.]]></Note>
        <Returns><![CDATA[apple]]></Returns>
       <Expression><![CDATA[ <sc>Food [1] </sc>]]></Expression>
        <Note><![CDATA[Accesses the Matrix value with index 1.]]></Note>
        <Returns><![CDATA[orange]]></Returns>
        <Expression><![CDATA[ <sc>Food [1 0]</sc>]]></Expression>
        <Note><![CDATA[Accesses the Matrix value with index [1 0].]]></Note>
        <Returns><![CDATA[lemon]]></Returns>
        <Expression><![CDATA[ <sc>#&#60Matrix 123456&#62[0]        </sc>]]></Expression>
        <Note><![CDATA[Instead of the Matrix  name, the object ID may be used to 

              access the Matrix  values]]></Note>
        <Returns><![CDATA[apple]]></Returns>
        <Expression><![CDATA[ <sc>#&#60Matrix  123456&#62[1]      </sc>]]></Expression>
        <Note><![CDATA[Accesses the Matrix  value with index 1.]]></Note>
        <Returns><![CDATA[orange]]></Returns>
        <Expression><![CDATA[ <sc>#&#60Matrix  234567&#62[1]       </sc>]]></Expression>
        <Note><![CDATA[Accesses the Matrix  value with index 2.]]></Note>
        <Returns><![CDATA[orange]]></Returns>
        <Hints><![CDATA[The ref function can be used for all of the specialized Matrix types: 
         Number Matrices. An element in a Matrix can optionally be referenced with the []
         operator.   The brackets must contain a valid integer index to the specified Matrix
        element.]]></Hints>
   </Syntax>
</Example>
