=== rms1000watt/aiserver/aisdocsdev/trunk/DTD/Example.dtd
<?xml version="1.0" encoding="UTF-8"?>
 <!ELEMENT Example (KnowledgeBase, Description, Syntax)>
	 <!ELEMENT KnowledgeBase (Title, Template, FunctionKeywords, TypeKeywords, RelatedFunctions, Language, HumanKeywords)>
		<!ELEMENT Title (#PCDATA)>
		<!ELEMENT Template (#PCDATA)>
		<!ELEMENT FunctionKeywords (#PCDATA)>
		<!ELEMENT TypeKeywords (#PCDATA)>
		<!ELEMENT RelatedFunctions (#PCDATA)>
		<!ELEMENT Language (#PCDATA)>
		<!ELEMENT HumanKeywords (#PCDATA)>
	<!ELEMENT Description ANY>   
	<!ELEMENT Syntax ((Expression, Note, Returns)+,  Hints)>
		<!ELEMENT Expression ANY>
		<!ELEMENT Note ANY>
		<!ELEMENT Returns ANY>
		<!ELEMENT Hints ANY>
<!-- end -->

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_Directory_member_003.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example Directory member 003</Title>
		<Template>Example</Template>
		<FunctionKeywords>member</FunctionKeywords>
		<TypeKeywords>   Directory Boolean Symbol
Integer

</TypeKeywords>
		<RelatedFunctions>  inside isInside isMember</RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>Directory Equal Analytic Object </HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples check if the key is a member of the Directory using the





                  <b>member</b> function.
If the key is a member of the Directory, its


                  index value will be returned, if not the Boolean, false will be returned.



	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>(member SSN:  #{dir| Name: "John Doe" SSN "555 12 1324"}) </sc>]]></Expression>
        <Note><![CDATA[SSN: is a key in the Directory. The index value of the key is returned. ]]></Note>
        <Returns><![CDATA[1]]></Returns>
        <Expression><![CDATA[ <sc>(member  Address:  #{dir| Name: "John Doe"  SSN: 556-12-5151})         </sc>]]></Expression>
        <Note><![CDATA[Address: is a not key contained in the Directory. ]]></Note>
        <Returns><![CDATA[false ]]></Returns>
        <Hints><![CDATA[none  ]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_Character_ccompareGT_001.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example Character ccompareGT 001</Title>
		<Template>Example</Template>
		<FunctionKeywords>ccompareGT</FunctionKeywords>
		<TypeKeywords>Integer Boolean Character</TypeKeywords>
		<RelatedFunctions> ccompareEQ ccompareNE ccompareGE ccompareLT  ccompareLE</RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>compare Lambda greater character</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples use the <b>ccompareGT</b> function to compare two objects and return







                  the Boolean value, true if the first argument is greater than the second argument
                 or false if otherwise.  





	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>
(ccompareGT #\c #\d)         </sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[false]]></Returns>
 	    <Expression><![CDATA[ <sc>
(ccompareGT #\f #\d)</sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[true]]></Returns>
        <Expression><![CDATA[ <sc>(ccompareGT #\c #\c)  </sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[false]]></Returns>
        <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_Void_isEqual_006.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example Void isEqual 006</Title>
		<Template>Example</Template>
		<FunctionKeywords>isEqual</FunctionKeywords>
		<TypeKeywords>Void Boolean</TypeKeywords>
		<RelatedFunctions>compareEQ isIdentical comparison   </RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>Void Equal Analytic Object </HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples check if the value of the first Object





                   is equal to the corresponding value   of the second





                   Object. If they are, the function returns true, otherwise, it returns false.






 






	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>(isEqual x  #void)    </sc>]]></Expression>
        <Note><![CDATA[An uninitialized value is always equal to #void.]]></Note>
        <Returns><![CDATA[true]]></Returns>
        <Expression><![CDATA[ <sc>(isEqual  x  0)         </sc>]]></Expression>
        <Note><![CDATA[An uninitialized value is #void.  The value #void is always less than any value. ]]></Note>
        <Returns><![CDATA[ false ]]></Returns>
        <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_Vector_compareLE_006.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example Vector compareLE 006</Title>
		<Template>Example</Template>
		<FunctionKeywords>compareLE</FunctionKeywords>
		<TypeKeywords>Vector Boolean</TypeKeywords>
		<RelatedFunctions>compare compareEQ compareNE compareGE compareLT  compareGT </RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>compare symbol equal lesser </HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples use the <b>compareLE</b> function to compare two Vectors and return







                  the Boolean value, true or false.  The corresponding values of each Vector are compared




                  to determine whether one Vector is lesser than or equal to the other.




	]]></Description>
	<Syntax>
        <Expression><![CDATA[ <sc>(compareLE #("Hello" "World" ) #("Hello" "World" ))     </sc>]]></Expression>  
        <Note><![CDATA[Both Vectors are equal.]]></Note> 
        <Returns><![CDATA[true]]></Returns>
        <Expression><![CDATA[ <sc>(compareLE #("Hello" "Worlds" ) #("Hello" "World" ))     </sc>]]></Expression>  
        <Note><![CDATA[ The value of the first Vector is greater than the value
               of the second Vector.]]></Note> 
        <Returns><![CDATA[false]]></Returns>
        <Expression><![CDATA[ <sc>(compareLE #("Hello" "Earth" ) #("Hello" "World" ))    </sc>]]></Expression>  
        <Note><![CDATA[The value of the first Vector is lesser than the value
               of the second Vector.]]></Note> 
        <Returns><![CDATA[true]]></Returns>
      <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_Dictionary_binarySearch_002.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example Dictionary binarySearch 002</Title>
		<Template>Example</Template>
		<FunctionKeywords>binarySearch</FunctionKeywords>
		<TypeKeywords>Dictionary Symbol</TypeKeywords>
		<RelatedFunctions>insert binaryInsert sort uniqueInsert</RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>binary insert search   sort</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ Each one of these examples defines a sorted  Dictionary. Then it


                  uses the <b>binarySearch</b> function to search for a key


                  in the defined Dictionary.

	]]></Description>
	<Syntax>
  	   <Expression><![CDATA[ <sc>(binarySearch  #{dic|a:  4.2  c:  5.1}  b:)       </sc>]]></Expression>
        <Note><![CDATA[The key b: is not contained in the Dictionary]]></Note>
        <Returns><![CDATA[false]]></Returns>
        <Expression><![CDATA[ <sc>(binarySearch  #{dic|a:  4.2  c:  5.1}  a:)         </sc>]]></Expression>
        <Note><![CDATA[The key a: has index value 0 in the Dictionary.]]></Note>
        <Returns><![CDATA[0]]></Returns>
        <Hints><![CDATA[The Dictionary must have previously been sorted for the <b>binarySearch</b>
               function to work. ]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_ByteVector_isCharNumeric_003.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example ByteVector isCharNumeric  003</Title>
		<Template>Example</Template>
		<FunctionKeywords>isCharNumeric </FunctionKeywords>
		<TypeKeywords>Text Character String Symbol ByteVector </TypeKeywords>
		<RelatedFunctions>isType isChar isCharAlphabetic isCharAlphanumeric



                          isCharLowercase isCharName isCharUppercase isCharWhitespace



                          isString isText </RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>Character Alphabetic Object Uppercase Lowercase Name



                       Underscore Numeric Alphanumeric Name Whitespace</HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples check if the object is is made up numeric



                  characters. If it is,  the function returns true, otherwise, it returns false.



 



	]]></Description>
	<Syntax>
        <Expression><![CDATA[ <sc>(isCharNumeric  |1234|:)</sc>]]></Expression>
        <Note><![CDATA[The characters of the global value of the Symbol is made up of numbers. ]]></Note>
        <Returns><![CDATA[ true ]]></Returns>
        <Expression><![CDATA[ <sc>(isCharNumeric "4884") </sc>]]></Expression>
        <Note><![CDATA[The String is made up of numbers. ]]></Note>
        <Returns><![CDATA[ true ]]></Returns>
  	    <Expression><![CDATA[ <sc>(isCharNumeric   #\p)  </sc>]]></Expression>
        <Note><![CDATA[A Text object is evaluated.]]></Note>
        <Returns><![CDATA[false]]></Returns>
        <Expression><![CDATA[ <sc>(isCharNumeric  p3b4:) </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[ false ]]></Returns>
        <Expression><![CDATA[ <sc>(isCharNumeric  #&#60Dictionary 47917&#62) </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[ false ]]></Returns>
        <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_ShortVector_append_008.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example ShortVector append 008</Title>
		<Template>Example</Template>
		<FunctionKeywords>append</FunctionKeywords>
		<TypeKeywords>ShortVector</TypeKeywords>
		<RelatedFunctions>new replace rept</RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>append concatenate vector </HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[  This example takes 2 existing Short Vectors and appends 
                  the values of each Short Vector.  The result is placed in a new Short Vector.


	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>(setq X (new Vector:  short:  2 9 2))         </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[#&#60ShortVector 123456&#62 ]]></Returns>
        <Expression><![CDATA[ <sc>(setq Y (new Vector:  short:  4 4 3 1 5))          </sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[#&#60ShortVector 234567&#62   ]]></Returns>
        <Expression><![CDATA[ <sc> (append X Y )    </sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[#&#60ShortVector 456789&#62   ]]></Returns>
        <Expression><![CDATA[ <sc>(display #&#60ShortVector 456789&#62 )       </sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[#(short| 9 2 4 3 1 5 )]]></Returns>
        <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>

=== rms1000watt/aiserver/aisdocsdev/trunk/CoreContent/Example_NumMatrix_isEqual_020.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Example SYSTEM "../DTD/Example.dtd">
<Example>
	<KnowledgeBase>
		<Title>Example NumMatrix isEqual 020</Title>
		<Template>Example</Template>
		<FunctionKeywords>isEqual</FunctionKeywords>
		<TypeKeywords>NumMatrix Boolean</TypeKeywords>
		<RelatedFunctions>compareEQ isIdentical comparison   </RelatedFunctions>
		<Language>Lisp</Language>
		<HumanKeywords>NumMatrix Equal Analytic Object </HumanKeywords>
	</KnowledgeBase>
	<Description><![CDATA[ These examples check if the value of the first NumMatrix





                   is equal to the corresponding value   of the second





                   NumMatrix. If they are, the function returns true, otherwise, it returns false.






 






	]]></Description>
	<Syntax>
  	    <Expression><![CDATA[ <sc>(isEqual  #(nummat| 3 -9 ) #(nummat| 3.0 -9.0 ))    </sc>]]></Expression>
        <Note><![CDATA[none]]></Note>
        <Returns><![CDATA[true]]></Returns>
        <Expression><![CDATA[ <sc>(isEqual  #(nummat| 3 -9 4.0 ) #(nummat| 3.0 -9.0 ))       </sc>]]></Expression>
        <Note><![CDATA[none ]]></Note>
        <Returns><![CDATA[ false ]]></Returns>
        <Hints><![CDATA[none]]></Hints>
   </Syntax>
</Example>
